server:
  port: 8082

spring:
  application:
    name: bookstore-payments

  datasource:
    url: jdbc:postgresql://postgres:5432/bookstore
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: discovery
  client:
    service-url:
      defaultZone: http://discovery:8070/eureka
