server:
  port: 8081

spring:
  application:
    name: orders

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
